//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MosFontTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MosFontTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error....
        /// </summary>
        internal static string Caption_error {
            get {
                return ResourceManager.GetString("Caption_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export complete.
        /// </summary>
        internal static string Caption_exportMsg {
            get {
                return ResourceManager.GetString("Caption_exportMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hine.
        /// </summary>
        internal static string Caption_info {
            get {
                return ResourceManager.GetString("Caption_info", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap colorPicker {
            get {
                object obj = ResourceManager.GetObject("colorPicker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap complete {
            get {
                object obj = ResourceManager.GetObject("complete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input background color..
        /// </summary>
        internal static string Err_backcolor_required {
            get {
                return ResourceManager.GetString("Err_backcolor_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input chars..
        /// </summary>
        internal static string Err_char_required {
            get {
                return ResourceManager.GetString("Err_char_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select font..
        /// </summary>
        internal static string Err_font_required {
            get {
                return ResourceManager.GetString("Err_font_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input forecolor.
        /// </summary>
        internal static string Err_forecolor_required {
            get {
                return ResourceManager.GetString("Err_forecolor_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color mode validation failure..
        /// </summary>
        internal static string Err_invalidateColorMode {
            get {
                return ResourceManager.GetString("Err_invalidateColorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scan mode validation failure..
        /// </summary>
        internal static string Err_invalidateScanMode {
            get {
                return ResourceManager.GetString("Err_invalidateScanMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select size..
        /// </summary>
        internal static string Err_size_required {
            get {
                return ResourceManager.GetString("Err_size_required", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap fontViewr {
            get {
                object obj = ResourceManager.GetObject("fontViewr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon fontViewrIcon {
            get {
                object obj = ResourceManager.GetObject("fontViewrIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MosFontTool
        ///
        ///  by mostone@hotmail.com.
        /// </summary>
        internal static string Inf_about {
            get {
                return ResourceManager.GetString("Inf_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input array name..
        /// </summary>
        internal static string Inf_arrayName_required {
            get {
                return ResourceManager.GetString("Inf_arrayName_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select color mode..
        /// </summary>
        internal static string Inf_colorMode_required {
            get {
                return ResourceManager.GetString("Inf_colorMode_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font array export complete.
        ///
        ///Do you want to open output file?.
        /// </summary>
        internal static string Inf_openFileConfirm {
            get {
                return ResourceManager.GetString("Inf_openFileConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select scan mode..
        /// </summary>
        internal static string Inf_scanMode_required {
            get {
                return ResourceManager.GetString("Inf_scanMode_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MosFontTool
        ///  By mostone@hotmail.com
        ///
        ///ABCDEFGHIJKLMNOPQRSTUVWXYZ
        ///abcdefghijklmnopqrstuvwxyz
        ///0123456789
        ///~!@#$%^&amp;*()_+
        ///心静自然凉.
        /// </summary>
        internal static string inputChars {
            get {
                return ResourceManager.GetString("inputChars", resourceCulture);
            }
        }
    }
}
